name: Build and Deploy Azure Function App

on:
  push:
    branches:
      - master

env:
  OUTPUT_PATH: ${{ github.workspace }}/.output
  DOTNET_VERSION: '3.1.100'
  AZURE_FUNCTIONAPP_NAME: sharemarketliveupdates
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '../../ShareMarketLiveUpdates.Functions'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
        - name: 'Checkout'
          uses: actions/checkout@master

        - name: Setup Dotnet ${{ env.DOTNET_VERSION }} Environment
          uses: actions/setup-dotnet@v1
          with:
              dotnet-version: ${{ env.DOTNET_VERSION }}

        - name: 'Resolve Project Dependencies and Build'
          shell: pwsh
          run: |
            pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
            dotnet build --configuration Release --output ./output
            popd

        - name: 'Run Azure Functions Action'
          uses: Azure/functions-action@v1
          id: fa
          with:
            app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
            package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
            publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
